name: Build & Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pinging deploy api
        run: |
          curl --request GET \
            --url ${{ secrets.API_ROUTE }} \
            --header 'X-Token:  ${{ secrets.X_TOKEN }}'
